osTicket/docs

_themes/sphinx_rtd_theme/footer.html

This adds links to Enhancesoft and osTicket in the theme footer.

Linked Footer

---

_static/css/main.css

This addresses and issue where you couldn't easily tell what tab you're
on. This adds a background color of white to the tab you're on for
better visibility.

issue: Active Tab Highlighting

---

Admin/Manage/Ticket Filters.rst
Getting Started/Installation.rst

Edited Admin > Manage > Filter Actions.

Edited Admin > Manage > Ticket Filters > Filter Actions.

---

Admin/Agents/Roles.rst

Edited Admin > Agents > Roles.

Edited Admin > Agents > Roles. Now in alphabetical Order.

---

Getting Started/Upgrade and Migration.rst

Looks like Step 8 and 9 were split into two steps when they were a single step.  Merged them, and added a new step 9 to cover newer versions.

Update Upgrade and Migration.rst

---

Agent/Dashboard/My Profile.rst

This adds full documentation for the Reply Redirect Setting.

Documentation for Reply Redirect Setting

---

Getting Started/Email Templates.rst

This adds documentation for the Complete Thread Variable.

Documentation for Complete Thread Variable

---

Getting Started/v1-12-2 Overview.rst
index.rst

This updates the Upgrade Overview from v1.11 to v1.12.2, it's time to get serious.

update: Upgrade Overview

---

Admin/Agents/Teams.rst

This updates Admin > Agents > Teams documentation.

update: Admin Agents Teams

---

Admin/Settings/System.rst

This adds full documentation for the Allow iFrames Option.

Documentation for Allow iFrames Option

---

Getting Started/Installation.rst

Embed the installation video in the installation guide.

Installation Video

---

Developer Documentation/API/Tickets.rst
Getting Started/Email Settings.rst
Getting Started/Installation.rst
Getting Started/POP3-IMAP Settings.rst
Getting Started/Upgrade and Migration.rst

This updates all of the outdated links in the Documentation.

update: Outdated Links

---

Getting Started/Installation.rst

Add the Windows IIS installation video to the docs.

IIS Installation Video

---

Getting Started/Email Settings.rst

Add video tutorial for Gmail email configuration

Gmail Email Configuration

---

Getting Started/POP3-IMAP Settings.rst

update Auto cron section to point to correct place.

Update POP3-IMAP Settings.rst

---

Admin/Manage/Plugins.rst

Add plugin tutorial video to plugins section of documenation.

Plugin Tutorial

---

make.bat

This addresses issue #30 by adding a Windows Makefile called `make.bat`.

add: Make.bat

---

Plugins/Audits.rst

Add the audit log video tutorial to the documentation.

Audit Plugin Tutorial

---

Features/Ticket Merge & Link.rst

Add the ticket merge/link tutorial video to the documentation.

Ticket Merge/Link Tutorial

---

Admin/Manage/Ticket Filters.rst

Add the ticket filter video to the documentation.

Ticket Filter Video

---

Getting Started/Upgrade and Migration.rst

Add the upgrade tutorial to the documentation.

Upgrade Video

---

Getting Started/Email Settings.rst

Add the outlook email configuration video to the documentation.

Outlook Email Configuration

---

Admin/Manage/Lists.rst

Updated `Admin Panel > Manage > Lists`.

update: Manage Lists

---

Admin/Agents/Roles.rst

update: Admin Agents Roles

---

Agent/Knowledgebase/Knowledgebase.rst

update: Agent Knowledgebase

---

Admin/Agents/Agents.rst

Updated `Admin Agents Agents`.

update: Admin Agents Agents

---

Admin/Agents/Departments.rst

update: Admin Agents Depts

---

Admin/Settings/Tickets.rst

Updated 'Admin Settings Tickets'.

update: Admin Settings Tickets

---

Features.rst
index.rst

This rearranges the Features for `1.14.x` so that only New Features relevant to the series are in the list. All other features will be listed under the Previously Released section.

features: Rearrange 1.14.x

---

Getting Started/v1-14-2 Overview.rst

This rewords some of the information in the Agent Collab Feature Overview.

reword: Agent Collab Feature Overview

---

Agent/Tickets/Advanced Search.rst

Add the advanced search video to the documentation.

Advanced Search Tutorial

---

Features/Custom Columns & Custom Queues (Agent).rst

Add Personal Queue Video to documentation

Personal Queue Video

---

index.rst

Add the documentation for Visibility Permissions to the Features list.

Visibility Permissions

---

Admin/Manage/Forms.rst

Update: Admin > Manage > Forms.

---

Features/Multifactor Authentication.rst

This commit adds the Eamil 2FA video to the documentation.

Add Email 2FA Video

---

Plugins/Attachments on the Filesystem.rst

This commit adds the youtube video for Attachments on the Filesystem plugin to the docs.

Add Video To Filesystem Plugin

---

Features/Ticket Referral.rst

Add Referral video to documentation.

Referral Video

---

Features/Agent CSV Export.rst
Features/Create Ticket or Task from Thread Entry.rst
Features/Department CSV Export.rst
Features/Release Assignment.rst

Features:
Agent CSV Export
Department CSV Export
Create Ticket or Task from Thread Entry
Release Assignment

Add Videos to Documentation

---

conf.py

This updates the copyright from 2020 to 2021.

update: Copyright 2021

---

Agent/Tickets/Tickets.rst

Updated `Agent Panel > Tickets Tab > Tickets`

update: Agent Panel > Tickets

---

Admin/Settings/Agents.rst

Updated: `Admin > Settings > Agents`

update: Admin > Settings > Agents

---

Agent/Dashboard/My Profile.rst

Updated: `Agent > Dashboard > Profile`

update: Agent > Dashboard > Profile

---

Admin/Emails/Emails.rst

updated: `Admin > Emails > SMTP Settings`

update: Admin > Emails

---

Admin Panel.rst
Admin/Manage/Schedules.rst
Features.rst

This moves Schedules from the Previously Released section to it's own tab under Admin Panel > Manage.

update: Schedules New Tab

---

Admin/Emails/Emails.rst

updated: `Admin Panel > Emails > Fetch from mailfolder`

Update: Admin Panel > Emails

---

Guides/Alerts Guide.rst

This addresses a build error where the image paths were incorrect.

issue: Incorrect Image Paths

---

conf.py

This updates the Copyright from 2021 to 2022.

update: Copyright 2022

---

Agent/Users/User Directory.rst

Updated/User Directory

---

Guides/Translation Guide.rst
index.rst

This adds the Translation Guide to the toctree and adds a proper title.

issue: Translation Guide

---

Admin/Agents/Agents.rst
Getting Started/Email Piping.rst
Plugins/Attachments in S3.rst
Plugins/Attachments on the Filesystem.rst
Plugins/Password Management Policies.rst

This does some general cleanup; fixing warning and errors shown when building.

issue: General Cleanup

---

Guides/OAuth2 Guide.rst
Guides/SSO Guide.rst
OAuth2/Google Authentication (SSO) Guide.rst
OAuth2/Google Authorization Guide.rst
OAuth2/Microsoft Authentication (SSO) Guide.rst
OAuth2/Microsoft Authorization Guide.rst
index.rst

This adds the skeleton for all the OAuth2 changes to the documentation.

add: OAuth2 Guide Skeleton

---

Getting Started/Installation.rst

This removes the Installation videos for now until we have updated ones.

issue: Remove Install Videos

---

Getting Started/Installation.rst

This updates all the prerequisite links to match the latest versions and URLs.

update: Prerequisite Links

---

Getting Started/Installation.rst

This updates the Prereq Download Links from individual release links to general Download page links. This cuts down the need to update these so often as well as letting the User choose their own package/version.

update: Prereq Download Links

---

Admin/Agents/Departments.rst

This updates the Department documentation to include information about Alerts & Notices.

update: Department Alerts & Notices
